sudo: false
dist: trusty
cache:
  apt: true
env:
  global:
  - SPHINXBUILD=~/.local/bin/sphinx-build
  - secure: Nn985mEk01BbYLY7IQToa51+jpVp8/f72Q+SY6GVe1cf41gRG4CWrrLFLo4Zrdd+e5a9tMKJ2o6WqT4m0i1AziVnoFx62QtC0dmJVsp4eVzQdhWkaRTcLdoKp18om0To6cVmBzYFzsIUROyOwwJfprpzwylQGFqNFoNG20UmnzTy5c/bg36Ohh/vcpt3HXO6emKDTychu1fBC8tuiy7k5BCfPekKAg6sKTqjsgKM+pEZuv9zTzrBY0HVqCoSLhWUraADko51baOtbBOzLtH4L4EO1rmiFs7/HpN/MzF6REurCAbBM5q82aS/z5KUoMGENt+OwWbeT9BcqUty1wYAFwuK7UwkDO2+YauqGhZ75GKOt213Fdn70Wx1xMkOerdEb8oSdH8Av/FWxwbfI6qxsAhjimYTZ5OCCZu06AVMBugxBnZeYxF89+83qVUxCHNGyGnql1PHJnlIiOzmCmcgjFo90u9fv24497m9O9QlEic/PnN0VLogPOftgcRUdoLjsYh9P6+BvXrWQ0omu41UwnzNJERaeUXuXV+iJsj6kBuj1j6EJ7OK4RyS/Td8mC7sGFBdwOX+HLaPqBTD2rm7z0wtST0jyFJjPfmvCU94+ovpCuYeMxgeudnUXT8T26v6v73nk7QLIIYm1Idg2ibSBfQy5IT220sH6291IryoY2c=
git:
  depth: false
addons:
  apt:
    packages:
    - python3-pip
    - latexmk
    - libalgorithm-diff-perl
    - texlive
    - texlive-latex-extra
    - texlive-humanities
    - texlive-generic-recommended
    - texlive-generic-extra
install:
- pip3 install --user mako
- pip3 install --user typing
- pip3 install --user Sphinx==2.4.4
script:
- make latexpdf
- make html
- make singlehtml
before_deploy:
- cp build/latex/ebbr.pdf build/ebbr-$TRAVIS_TAG.pdf
deploy:
- provider: releases
  prerelease: true
  api_key:
    secure: M2Bwy2f0QUC6aDgMLwy2us6fqvzDFv08wDLfPtdq7Px/Xk6xHPOAKJ8xVbwn7f7wJI6jwtusXQUi8npczfiw5c6Pr/VQj/nVoS+IR1DPrxA+zWniMUYhOxoPTmQwYafDjSKr+89DFq15CVkYRUGb5F6snCEmG/VcpMA/u6CvyN7A+w+04twEY2HB6xjnw8rp45yJMO/Xl2tFrHXP6ofF0ezkfbKFXI+mPXp7A3byCLRk80JkxEyVNZVOJKFFO33uZBQo27MZpGtqk92zqetTTgOZDc9mUGjjz98+wKGKR7hN+h/866QU5M3U5abs7ZpnncedMf/MBkoXBT7xP/Wu5CJg2XYT5hPCOmmE97rz+E28xhbxzYUpnT8kXcGWlQamwQfBdakfPYcswHx5VwjGGSPsh9TU6rWEscjuhfkLeRzcLanl0Doeai2eKKg+1/Qfp123lBnorZLZUZr/g75Xhzd96aE8KxJL+J2Kyx3U6mC+ycBDHKBiQudCsBAL7ybw9CSwpLA6eR6nOAcupz0RuGPSy1T0wCxrxI2GI9NOdOC2IgREAIelEfSP32LNn2Uu+kFSA28zV5kDTaUP5/9vSxZkBOdTz0K3yG8Vha/gJIQx+hl4A3FtYWbIdW9GCMbJcMWuXUFLSwcVUXqoc1tsIvqBrSoYpDnNXK/ma0hYicg=
  file_glob: true
  file:
  - build/ebbr-*.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: upstream
    repo: glikely/ebbr
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/singlehtml
  skip_cleanup: true
  on:
    branch: master
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/singlehtml
  skip_cleanup: true
  repo: arm-software/ebbr
  on:
    branch: upstream
